version: '2.2'

services:

  applications:
    image: tianon/true
    volumes:
      - d:/WWW/Code/soap/management-frontend-lanqb:/var/www/management-frontend-lanqb
      - d:/WWW/Code/soap/copartner-backend-lanqb:/var/www/copartner-backend-lanqb
      - d:/WWW/Code/soap/user-management-backend-lanqb:/var/www/user-management-backend-lanqb
      - d:/WWW/Code/soap/school-backend-lanqb:/var/www/school-backend-lanqb
      - d:/WWW/Code/soap/resource-management-backend-lanqb:/var/www/resource-management-backend-lanqb
      - d:/WWW/Code/soap/business-shop-backend-lanqb:/var/www/business-shop-backend-lanqb
      - d:/WWW/Code/soap/bill-project:/var/www/bill-project
      - d:/WWW/Code/soap/main-website-frontend-lanqb:/var/www/main-website-frontend-lanqb
      - d:/WWW/Code/soap/sales-backend-lanqb:/var/www/sales-backend-lanqb
      - d:/WWW/Code/soap/lanqb-pay-gateway:/var/www/lanqb-pay-gateway
      - d:/WWW/Code/soap/soap-payment-system-lanqb:/var/www/soap-payment-system-lanqb
      - d:/WWW/Code/soap/mobile-frontend-lanqb:/var/www/mobile-frontend-lanqb
      - d:/WWW/Code/soap/earning-backend-lanqb:/var/www/earning-backend-lanqb
      - d:/WWW/Code/soap/test-cli:/var/www/test-cli
      - d:/WWW/Code/soap/maestro-api-gateway:/var/www/maestro-api-gateway
      - d:/WWW/Code/soap/classroom-backend:/var/www/classroom-backend

  es01:
    container_name: es01
    image: docker.elastic.co/elasticsearch/elasticsearch:6.5.0
    environment:
      - node.name=es01
      - discovery.zen.minimum_master_nodes=2
      - ELASTIC_PASSWORD=$ELASTIC_PASSWORD
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - xpack.license.self_generated.type=trial
      - xpack.security.enabled=true
      - xpack.security.http.ssl.enabled=false
      - xpack.security.transport.ssl.enabled=true
      - xpack.security.transport.ssl.verification_mode=certificate
      - xpack.ssl.certificate_authorities=$CERTS_DIR/ca/ca.crt
      - xpack.ssl.certificate=$CERTS_DIR/es01/es01.crt
      - xpack.ssl.key=$CERTS_DIR/es01/es01.key
    volumes:
      - esdata1:/usr/share/elasticsearch/data
      - ./certs:$CERTS_DIR
      - ./x-pack/x-pack-core-6.5.0.jar:/usr/share/elasticsearch/modules/x-pack-core/x-pack-core-6.5.0.jar
    networks:
      - esnet
    ports:
      - 9200:9200
    healthcheck:
      test: curl --cacert $CERTS_DIR/ca/ca.crt -s https://localhost:9200 >/dev/null; if [[ $$? == 52 ]]; then echo 0; else echo 1; fi
      interval: 30s
      timeout: 10s
      retries: 5

  es02:
    container_name: es02
    image: docker.elastic.co/elasticsearch/elasticsearch:6.5.0
    environment:
      - node.name=es02
      - discovery.zen.minimum_master_nodes=2
      - ELASTIC_PASSWORD=$ELASTIC_PASSWORD
      - discovery.zen.ping.unicast.hosts=es01
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - xpack.license.self_generated.type=trial
      - xpack.security.enabled=true
      - xpack.security.http.ssl.enabled=false
      - xpack.security.transport.ssl.enabled=true
      - xpack.security.transport.ssl.verification_mode=certificate
      - xpack.ssl.certificate_authorities=$CERTS_DIR/ca/ca.crt
      - xpack.ssl.certificate=$CERTS_DIR/es02/es02.crt
      - xpack.ssl.key=$CERTS_DIR/es02/es02.key
    networks:
      - esnet
    volumes:
      - esdata2:/usr/share/elasticsearch/data
      - ./certs:$CERTS_DIR
      - ./x-pack/x-pack-core-6.5.0.jar:/usr/share/elasticsearch/modules/x-pack-core/x-pack-core-6.5.0.jar

  kibana:
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:6.5.0
    environment:
      ELASTICSEARCH_URL: "http://es01:9200"
      ELASTICSEARCH_USERNAME: "elastic"
      ELASTICSEARCH_PASSWORD: $ELASTIC_PASSWORD
      ELASTICSEARCH_SSL_CERTIFICATEAUTHORITIES: "$CERTS_DIR/ca/ca.crt"
    ports:
      - 5601:5601
    volumes:
      - ./certs:$CERTS_DIR
    networks:
      - esnet
    depends_on:
      - es01

  logstash:
    image: docker.elastic.co/logstash/logstash:6.5.0
    container_name: logstash
    environment:
      LS_JAVA_OPTS: "-Xmx512m -Xms512m"
      XPACK_MANAGEMENT_ELASTICSEARCH_URL: http://es01:9200
      XPACK_MANAGEMENT_ELASTICSEARCH_USERNAME: "elastic"
      XPACK_MANAGEMENT_ELASTICSEARCH_PASSWORD: $ELASTIC_PASSWORD
      XPACK_MANAGEMENT_ENABLED: "true"
      XPACK_MANAGEMENT_PIPELINE_ID: "[main,php-logs]"
      XPACK_MONITORING_ENABLED: "true"
      XPACK_MONITORING_ELASTICSEARCH_URL: http://es01:9200
      XPACK_MONITORING_ELASTICSEARCH_USERNAME: "elastic"
      XPACK_MONITORING_ELASTICSEARCH_PASSWORD: $ELASTIC_PASSWORD
#      XPACK_MONITORING_ELASTICSEARCH_SSL_CA: "$CERTS_DIR/ca/ca.crt"
#      XPACK_MANAGEMENT_ELASTICSEARCH_SSL_CA: "$CERTS_DIR/ca/ca.crt"
    networks:
      - esnet
    volumes_from:
      - applications
    depends_on:
      - es01

  wait_until_ready:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.5.0
    command: /usr/bin/true
    depends_on:
      es01:
        condition: "service_healthy"

volumes:
  esdata1:
    driver: local
  esdata2:
    driver: local

networks:
  esnet:

